### ISSUE TITLE
Broken app when installing aurelia-firebase

### ISSUE THREAD

**Issue by kiquetal** [Thanood/aurelia-mdl-skeleton-navigation#22]
Hi, I want to use the aurelia-firebase plugin when, just after install via jspm, the ui broken, i've to reinstall the aurelia-mdl-skeleton-navigation

system.js:4 Uncaught (in promise) Error: (SystemJS) TypeError: Reflect.getOwnMetadata is not a function
        at Object.getOwn (http://localhost:9000/jspm_packages/npm/aurelia-metadata@1.0.0-rc.1.0.1/aurelia-metadata.js:46:22)
        at Object.getOrCreateOwn (http://localhost:9000/jspm_packages/npm/aurelia-metadata@1.0.0-rc.1.0.1/aurelia-metadata.js:52:29)
        at deco (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:3890:41)
        at bindable (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:3909:14)
        at defineProperties (http://localhost:9000/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.0.3/compose.js:7:624)
        at eval (http://localhost:9000/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.0.3/compose.js:7:1056)
        at eval (http://localhost:9000/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.0.3/compose.js:16:5)
        at Object.eval (http://localhost:9000/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.0.3/compose.js:137:5)
    Error loading http://localhost:9000/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.0.3.js

**Comment by Thanood** [comment]
Hi @kiquetal,

unfortunately this repo is not updated anymore and it still uses the old `<content>` elements which won't work with Aurelia RC1 since that version uses `<slot>`.

At least I _guess_ that this is the reason. :smile: 
You could try to replace all `content` with `slot` and see if it works.

I'd also merge a PR if you feel like changing and uploading it. :smile:
